name: push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify js
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: "js"
      
      - name: Auto Minify css
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: "css"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy
        run: aws s3 sync . s3://logoscode.com.mx --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore" --exclude "css/bootstrap.css.map" --exclude "css/bootstrap.scss" --delete --only-show-errors
