name: push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Minify files
        run: |
          sudo apt-get -y install moreutils
          minify ./js/master.js | sponge ./js/master.js
          minify ./css/master.css | sponge ./css/master.css
          minify ./css/bootstrap.css | sponge ./css/bootstrap.css
          minify index.html | sponge index.html
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy
        run: aws s3 sync . s3://www.logoscode.com.mx --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore" --exclude "css/bootstrap.css.map" --exclude "css/bootstrap.scss" --delete --only-show-errors
